version: '3'

services:
  docker-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bootdb"
      MYSQL_USER_ROOT: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - 3306:3306
    networks:
      - mysql-compose-network
      
  app:
    image: lucasvilela/stock-manager
    ports:
      - 8080:8080
    depends_on:
      - docker-mysql
    networks:
      - mysql-compose-network

  my-app:
    build:
      dockerfile: Dockerfile
      context: .
    image: stock-quote-manager:1.0
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL:jdbc:docker-mysql://localhost:3306/bootdb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    depends_on:
      - docker-mysql
      - app
    networks:
      - mysql-compose-network
      
networks: 
  mysql-compose-network:
    driver: bridge